name: build hogwarp
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - Docker-Images/Hogwarp/**
jobs:
  push:
    name: "hogwarp:release"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-latest
          - debian-10
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Docker-Images/Hogwarp
          file: ./Docker-Images/Hogwarp/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/imkringle/hogwarp:release
