name: build tuxlauncher
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - Docker-Images/tuxlauncher/**
jobs:
  push:
    name: "tuxlauncher:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-latest
          - debian-10
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Docker-Images/tuxlauncher
          file: ./Docker-Images/tuxlauncher/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/imkringle/tuxlauncher:latest
